server:
  port: 8080
spring:
  h2.console:
    enabled: true
    path: /console
  datasource:
    url: jdbc:h2:file:C:/dev/projects/workout-plan/workout-plan
  jpa:
    hibernate:
      ddl-auto: validate

